enum RESOURCES_TYPE {
  PRESS = 'PRESS',
  AFFILIATE = 'AFFILIATE',
  SUPPORT = 'SUPPORT',
  TERMS = 'TERMS',
  POLICY = 'POLICY',
  ABOUT = 'ABOUT',
  SAFETY = 'SAFETY',
  COOKIE = 'COOKIE',
}

export default RESOURCES_TYPE;
