export type IMyChoice = {
  haveAHome: string;
  liveAlone: string;
  liveWithParents: string;
  christian: string;
  believeJesusIsHead: string;
  numberOfChildrenWanted: number;
  manIsMainProvider: string;
  stepUpAsMother: string;
  stepUpAsFather: string;
  menRoleModelsForBoys: string;
  menSetStandardForDaughters: string;
  mothersAreNurturers: string;
  womenMakeHome: string;
  willingToWork: string;
  interestsHobbies: string;
  preferredAgeRange: string;
  preferredEthnicity: string;
  preferHomesteadingOrUrban: string;
  preferredPhysique: string;
  preferredFitnessLevel: string;
  willingToStepUpForOtherChildren: string;
};
